export const INITIAL_DATA = {
  header: {
    titulo1: "Día de la Madre",
    titulo2: "Chalaysanta",
    sub: "Informe de Comisiones de Trabajo · Estado y Responsabilidades",
    fechaEvento: "09 Mayo 2026",
    fechaISO: "2026-05-09T10:00:00",
    fecha: "09 de Mayo, 2026",
    ubicacion: "Av. Arequipa 757, San Jerónimo",
    estado: "5 completas · 2 con pendientes",
  },
  alertas: {
    fecha1: "02 / 05 / 2026",
    desc1: "Entrega de requerimientos de cada comisión",
    fecha2: "04 / 05 / 2026",
    desc2: "Presentación de informe de avance de trabajo por comisión",
  },
  footer: {
    nombre: "Día de la Madre Chalaysanta",
    lugar: "San Jerónimo de Tunán",
    fecha: "09 de Mayo 2026",
    minuta: "Minuta N° 003",
  },
  images: { cover: "", footer: "" },
  comisiones: [
    {
      id: 1,
      titulo: "Comisión de Ambientación",
      titular: "Elizabeth Villarroel",
      status: "complete",
      tareas: [
        "Armada de carpa y desarme al cierre del evento",
        "Sillas, panel, globos, mesa y banners",
        "Carpa: 4 varones asignados",
        "Decoración: 4 mujeres (panel, globos, cintas)",
      ],
      personal: "8 personas (4 varones + 4 mujeres)",
      apoyo: "",
      entrega: "02 / 05 / 2026",
      informe: "04 / 05 / 2026",
      alerta: "",
      requerimientos: [
        { nombre: "Carpa 6x6m", detalle: "Con estructura metálica", cantidad: "1 unidad", monto: "", done: false },
        { nombre: "Sillas plásticas", detalle: "", cantidad: "80 unidades", monto: "", done: false },
        { nombre: "Globos decorativos", detalle: "Colores del evento", cantidad: "200 unidades", monto: "", done: false },
        { nombre: "Banners", detalle: "Con diseño institucional", cantidad: "3 unidades", monto: "", done: true },
      ],
    },
    {
      id: 2,
      titulo: "Comisión de Soporte Técnico",
      titular: "Luis Páez",
      status: "complete",
      tareas: [
        "Equipo de sonido: transporte y devolución",
        "Recepción del elenco: coordinar con propietario de danza",
        "Generador eléctrico y extensiones",
      ],
      personal: "",
      apoyo: "1 ayudante",
      entrega: "02 / 05 / 2026",
      informe: "04 / 05 / 2026",
      alerta: "",
      requerimientos: [
        { nombre: "Equipo de sonido", detalle: "Altavoces, mezcladora y micrófonos", cantidad: "1 set", monto: "", done: false },
        { nombre: "Generador eléctrico", detalle: "2500W mínimo", cantidad: "1 unidad", monto: "", done: false },
        { nombre: "Extensiones eléctricas", detalle: "10 metros c/u", cantidad: "4 unidades", monto: "", done: true },
      ],
    },
    {
      id: 3,
      titulo: "Comisión de Recepción",
      titular: "Rossana Peñaloza",
      status: "missing",
      tareas: [
        "Recepción, gafete y entrega de ticket a asistentes",
        "Ubicar y dirigir a las personas según sector",
        "Organizar y gestionar 4 sectores del local",
      ],
      personal: "4 ayudantes + apoyo del Sr. Tito",
      apoyo: "",
      entrega: "02 / 05 / 2026",
      informe: "04 / 05 / 2026",
      alerta: "Personal incompleto — se requieren refuerzos urgentes",
      requerimientos: [
        { nombre: "Tickets de ingreso", detalle: "Impresos con numeración", cantidad: "150 unidades", monto: "", done: false },
        { nombre: "Gafetes de identificación", detalle: "Para el personal de recepción", cantidad: "6 unidades", monto: "", done: false },
        { nombre: "Mesa de recepción", detalle: "Con mantel", cantidad: "1 unidad", monto: "", done: true },
      ],
    },
    {
      id: 4,
      titulo: "Comisión de Premios",
      titular: "Josep Castro",
      status: "complete",
      tareas: [
        "Banners de auspiciadores y tazas de reconocimiento",
        "Organización y custodia de regalos",
        "Coordinación del sorteo",
        "Recepción de taquillas y tickets",
      ],
      personal: "",
      apoyo: "2 mujeres asignadas",
      entrega: "02 / 05 / 2026",
      informe: "04 / 05 / 2026",
      alerta: "",
      requerimientos: [
        { nombre: "Tazas de reconocimiento", detalle: "Personalizadas con nombre del evento", cantidad: "10 unidades", monto: "", done: false },
        { nombre: "Canastas de regalo", detalle: "Para el sorteo principal", cantidad: "3 unidades", monto: "", done: false },
        { nombre: "Banner de auspiciadores", detalle: "2x1 m tela impresa", cantidad: "2 unidades", monto: "", done: true },
      ],
    },
    {
      id: 5,
      titulo: "Comisión de Limpieza",
      titular: "Todos los integrantes",
      status: "complete",
      tareas: ["Responsabilidad compartida por todos los integrantes del comité antes, durante y después del evento"],
      personal: "",
      apoyo: "",
      entrega: "02 / 05 / 2026",
      informe: "04 / 05 / 2026",
      alerta: "",
      singleCol: true,
      requerimientos: [
        { nombre: "Bolsas de basura", detalle: "Grandes, negras", cantidad: "20 unidades", monto: "", done: false },
        { nombre: "Escobas y recogedores", detalle: "", cantidad: "4 juegos", monto: "", done: true },
        { nombre: "Desinfectante", detalle: "Para pisos", cantidad: "2 litros", monto: "", done: false },
      ],
    },
    {
      id: 6,
      titulo: "Comisión de Alimentación",
      titular: "Irma Porras Filio",
      status: "missing",
      tareas: [
        "Preparación de ají de gallina (aprox. 50 platos)",
        "Preparación de refresco para el evento",
        "Break para elenco de danza: galletas y snacks",
      ],
      personal: "4 ayudantes (faltan 2 personas)",
      apoyo: "",
      entrega: "02 / 05 / 2026",
      informe: "04 / 05 / 2026",
      alerta: "Faltan 2 personas de apoyo — incorporación urgente",
      requerimientos: [
        { nombre: "Gallinas enteras", detalle: "Para el ají de gallina", cantidad: "5 unidades", monto: "", done: false },
        { nombre: "Insumos ají de gallina", detalle: "Pan, leche, ají amarillo, nueces", cantidad: "1 lote", monto: "", done: false },
        { nombre: "Refresco chicha morada", detalle: "Para 60 personas", cantidad: "15 litros", monto: "", done: false },
        { nombre: "Snacks para elenco", detalle: "Galletas y bebidas", cantidad: "1 paquete", monto: "", done: true },
      ],
    },
    {
      id: 7,
      titulo: "Comisión de Arte y Modelaje",
      titular: "Danitza Camarena",
      status: "complete",
      tareas: [
        "Organización del concurso de modelaje de madres",
        "Coordinación de premios: cartera y vales de joyería",
        "Dirección artística del modelaje",
      ],
      personal: "",
      apoyo: "Meyli Astucuri (1 ayudante)",
      entrega: "02 / 05 / 2026",
      informe: "04 / 05 / 2026",
      alerta: "",
      requerimientos: [
        { nombre: "Cartera de cuero", detalle: "Premio 1er lugar modelaje", cantidad: "1 unidad", monto: "", done: false },
        { nombre: "Vale de joyería", detalle: "Premio 2do y 3er lugar", cantidad: "2 vales", monto: "", done: false },
        { nombre: "Faja y corona", detalle: "Para la ganadora", cantidad: "1 set", monto: "", done: true },
      ],
    },
  ],
};
